const NO_TWITTER_TOKEN = 'NO_TWITTER_TOKEN';

const OFFLINE = 'OFFLINE';
const NO_TWITTER_SERVER = 'NO_TWITTER_SERVER';
const OAUTH_SUCCESS = 'OAUTH_SUCCESS';
const OAUTH_FAIL = 'OAUTH_FAIL';

const CONNECTING = 'CONNECTING';
const TIMEOUT = 'TIMEOUT';
const WRONG_STATUS = 'WRONG_STATUS';
const OK_STATUS = 'OK_STATUS';
const RATE_LIMITS = 'RATE_LIMITS';

const CONNECTED = 'CONNECTED';
const HEARTBEAT = 'HEARTBEAT';
const CHUNK = 'CHUNK';
const TWEET = 'TWEET';
const NOT_JSON = 'NOT_JSON';
const NOT_TWEET = 'NOT_TWEET';

const CONN_INACTIVE = 'CONN_INACTIVE';
const CONN_ACTIVE = 'CONN_ACTIVE';

const CONN_END = 'CONN_END';

export {
  OFFLINE,
  NO_TWITTER_SERVER,
  OAUTH_SUCCESS,
  OAUTH_FAIL,
  NO_TWITTER_TOKEN,
  CONNECTING,
  WRONG_STATUS,
  TIMEOUT,
  OK_STATUS,
  RATE_LIMITS,
  CONNECTED,
  HEARTBEAT,
  CHUNK,
  TWEET,
  NOT_JSON,
  NOT_TWEET,
  CONN_INACTIVE,
  CONN_ACTIVE,
  CONN_END,
};
